# apiVersion: v1
# kind: Service
# metadata:
#   name: shopping-cart
#   labels:
#     app: shopping-cart
# spec:
#   ports:
#     - port: 8000
#   selector:
#     app: shopping-cart
#   type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart
  labels:
    app: shopping-cart
spec:
  selector:
    matchLabels:
      app: shopping-cart
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
      - image: {{ required "Provide the shopping cart container image." .Values.images.shoppingcart }}
        name: shopping-cart
        imagePullPolicy: Always
        env:
        - name: MONGO_HOST
          value: shopping-cart-mongodb
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
        ports:
        - containerPort: 8008
          name: shopping-cart